swagger: "2.0"
info:
  title: "dev-backend-springboot"
  description: "API on API Gateway with an App Engine backend"
  version: "1.0.0"
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      responses:
        '200':
          description: OK
      x-google-backend:
        address: https://dev-backend-springboot.appspot.com
        protocol: h2
